env:
  es2021: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
settings:
  react:
    version: "detect"
